project_name: "TextSummarization"
random_seed: 42

data:
  dataset_name: "IlyaGusev/gazeta"
  text_column: "text"
  summary_column: "summary"
  train_split: "train[:10%]" 
  test_split: "test[:20%]"   
  max_source_length: 512    
  max_target_length: 128

model:
  name: "google/mt5-small"
  

training:
  output_dir: "./results"
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  load_best_model_at_end: True
  predict_with_generate: True
  report_to: "none"

evaluate:
  metrics_file: evaluation_metrics.json

logging:
  log_file: "val.log"
  level: "INFO"